using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using DungeonTavern.Prototypes.Rotation25D;
internal static class B1FloorCameraRepair {
const string Out="ArtSource/Previews/B1FloorCamera/";
static Scene B=>SceneManager.GetSceneByPath("Assets/Scenes/SealRoom/SealRoom_B1.unity");
static Transform[] All(Scene s)=>s.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).ToArray();
[MenuItem("Tools/Dungeon Tavern/Inspect B1 Floor Camera")]
static void Inspect(){Directory.CreateDirectory(Out);var sb=new StringBuilder();sb.AppendLine("Playing="+EditorApplication.isPlaying);var ground=All(B).Single(t=>t.name=="Ground_Cracked");foreach(var c in B.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Collider>(true)))if(c.bounds.size.x>5||c.name.Contains("Floor"))sb.AppendLine("Collider "+c.name+" active="+c.gameObject.activeInHierarchy+" enabled="+c.enabled+" trigger="+c.isTrigger+" "+c.bounds);foreach(var c in UnityEngine.Object.FindObjectsByType<Camera>()){sb.AppendLine(c.name+" position="+c.transform.position+" forward="+c.transform.forward+" ortho="+c.orthographic+" near="+c.nearClipPlane+" far="+c.farClipPlane+" size="+c.orthographicSize+" target="+c.targetTexture);var walls=All(B).Where(t=>t.name=="Walls_Stone").SelectMany(t=>t.GetComponentsInChildren<MeshFilter>());int behind=0,total=0;foreach(var f in walls)foreach(var v in f.sharedMesh.vertices){total++;if(Vector3.Dot(f.transform.TransformPoint(v)-c.transform.position,c.transform.forward)<c.nearClipPlane)behind++;}sb.AppendLine("Wall vertices behind near plane="+behind+"/"+total);}File.WriteAllText(Out+"inspect.txt",sb.ToString());}
[MenuItem("Tools/Dungeon Tavern/Check B1 Camera Repair")]
static void Check(){if(!EditorApplication.isPlaying)throw new Exception("Play required");var rig=UnityEngine.Object.FindAnyObjectByType<PrototypeCameraOrbit>();var c=rig.GetComponentInChildren<Camera>();var yaw=rig.CurrentCardinalYaw;var origin=rig.transform.position;var sb=new StringBuilder();int checks=0;try{foreach(float a in new[]{0f,22.5f,45f,90f,135f,180f,225f,270f,315f}){rig.RotateBy(Mathf.DeltaAngle(rig.CurrentCardinalYaw,a));foreach(var pos in new[]{origin,new Vector3(34,0,12),new Vector3(49,0,12),new Vector3(34,0,25),new Vector3(49,0,25)}){rig.transform.position=pos;foreach(var f in All(B).Single(t=>t.name=="Walls_Stone").GetComponentsInChildren<MeshFilter>())foreach(var v in f.sharedMesh.vertices){var depth=Vector3.Dot(f.transform.TransformPoint(v)-c.transform.position,c.transform.forward);if(depth<c.nearClipPlane||depth>c.farClipPlane)throw new Exception("Wall outside depth range");checks++;}var lengths=new[]{12f,18f,24f}.Select(z=>((Vector2)(c.WorldToScreenPoint(new Vector3(43,0,z))-c.WorldToScreenPoint(new Vector3(42,0,z)))).magnitude).ToArray();if(lengths.Max()-lengths.Min()>.01f)throw new Exception("Distance changes scale");}}}finally{rig.transform.position=origin;rig.RotateBy(Mathf.DeltaAngle(rig.CurrentCardinalYaw,yaw));}sb.AppendLine("Passed "+checks+" wall depth checks, 9 headings x 5 positions; near/far 1m projected size equal to 0.01px.");sb.AppendLine("Player movers="+UnityEngine.Object.FindObjectsByType<PrototypePlayerMover>().Length);File.WriteAllText(Out+"camera-check.txt",sb.ToString());}
[MenuItem("Tools/Dungeon Tavern/Show B1 Projection Reference")]
static void Grid(){if(!EditorApplication.isPlaying)throw new Exception("Play required");if(GameObject.Find("ProjectionReference"))return;var root=new GameObject("ProjectionReference");SceneManager.MoveGameObjectToScene(root,B);var mat=new Material(Shader.Find("Universal Render Pipeline/Unlit"));mat.SetColor("_BaseColor",Color.cyan);foreach(float z in new[]{14f,18f,22f}){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name="Parallel_Z"+z;g.transform.SetParent(root.transform);g.transform.position=new Vector3(42,.025f,z);g.transform.localScale=new Vector3(10,.008f,.025f);g.GetComponent<Renderer>().sharedMaterial=mat;UnityEngine.Object.Destroy(g.GetComponent<Collider>());}foreach(float x in new[]{37f,42f,47f}){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name="Parallel_X"+x;g.transform.SetParent(root.transform);g.transform.position=new Vector3(x,.025f,18);g.transform.localScale=new Vector3(.025f,.008f,8);g.GetComponent<Renderer>().sharedMaterial=mat;UnityEngine.Object.Destroy(g.GetComponent<Collider>());}}
}
