using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEngine.SceneManagement;
using DungeonTavern.Tavern25D;
internal static class B1StoneGates {
 const string Root="Assets/DungeonTavern/Art/Environment/Architecture/Doors/StoneGate/";
 const string Out="ArtSource/Previews/B1StoneGates/";
 static Scene Scene=>SceneManager.GetSceneByPath("Assets/Scenes/SealRoom/SealRoom_B1.unity");
 [MenuItem("Tools/Dungeon Tavern/Check And Preview B1 Stone Gates")]
 static void Check(){var gates=Scene.GetRootGameObjects().SelectMany(g=>g.GetComponentsInChildren<Transform>(true)).Where(t=>t.name=="StoneGate_01"||t.name=="StoneGate_02").ToArray();if(gates.Length!=2)throw new Exception("Expected two gates");var closed=AssetDatabase.LoadAssetAtPath<AnimationClip>(Root+"Closed.anim");var open=AssetDatabase.LoadAssetAtPath<AnimationClip>(Root+"Open.anim");var opening=AssetDatabase.LoadAssetAtPath<AnimationClip>(Root+"Opening.anim");try{foreach(var t in gates){opening.SampleAnimation(t.gameObject,1.1f);if(Mathf.Abs(t.Find("DoorPanel").localPosition.y-1.475f)>.01f)throw new Exception("Animation midpoint incorrect");closed.SampleAnimation(t.gameObject,0);}Physics.SyncTransforms();foreach(var t in gates){var ray=new Ray(t.TransformPoint(new Vector3(0,1.3f,-2)),t.forward);if(!t.GetComponentsInChildren<Collider>().Any(c=>c.Raycast(ray,out _,4)))throw new Exception("Closed gate has no collision");}Render("Closed");foreach(var t in gates)open.SampleAnimation(t.gameObject,0);Physics.SyncTransforms();foreach(var t in gates){var ray=new Ray(t.TransformPoint(new Vector3(0,1.3f,-2)),t.forward);if(t.GetComponentsInChildren<Collider>().Any(c=>c.Raycast(ray,out _,4)))throw new Exception("Open gate blocked");var p=t.Find("DoorPanel");var b=p.GetComponent<BoxCollider>();if(p.localPosition.y+b.center.y+b.size.y/2>5.95f||p.localPosition.y<2.7f||b.size.z>.5f)throw new Exception("Door outside chamber");}Render("Open");File.WriteAllText(Out+"check.txt","Both gates: opening midpoint, closed collision, open passage and complete chamber containment passed. Clips sampled in Edit Mode; no player Play Mode traversal test.");}finally{foreach(var t in gates){closed.SampleAnimation(t.gameObject,0);PrefabUtility.RecordPrefabInstancePropertyModifications(t.Find("DoorPanel"));}Physics.SyncTransforms();EditorSceneManager.SaveScene(Scene);}}
 static void Render(string suffix){var scene=Scene;var go=new GameObject("Temporary Gate Camera");SceneManager.MoveGameObjectToScene(go,scene);var c=go.AddComponent<Camera>();c.enabled=false;c.scene=scene;c.orthographic=true;c.orthographicSize=7.3f;c.nearClipPlane=.01f;c.farClipPlane=100;c.clearFlags=CameraClearFlags.SolidColor;c.backgroundColor=new Color(.12f,.14f,.16f);var center=new Vector3(49.2f,3.1f,18.65f);c.transform.position=center+new Vector3(-8,4,-3);c.transform.LookAt(center);go.AddComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>().SetRenderer(1);var lg=new GameObject("Temporary Gate Light");SceneManager.MoveGameObjectToScene(lg,scene);var light=lg.AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.8f;lg.transform.rotation=Quaternion.Euler(40,60,0);var rt=new RenderTexture(1200,900,24);rt.Create();var old=RenderTexture.active;var tex=new Texture2D(1200,900,TextureFormat.RGB24,false);try{UnityEngine.Rendering.RenderPipeline.SubmitRenderRequest(c,new UnityEngine.Rendering.Universal.UniversalRenderPipeline.SingleCameraRequest{destination=rt});RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1200,900),0,0);tex.Apply();File.WriteAllBytes(Out+suffix+".png",tex.EncodeToPNG());}finally{RenderTexture.active=old;UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(go);UnityEngine.Object.DestroyImmediate(lg);}}

}
