using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
internal static class BuildDungeonStoneWalls {
 const string Root="Assets/DungeonTavern/Art/Environment/Architecture/Walls/石墙/";
 const string Output="ArtSource/Previews/DungeonStoneWalls/";
 static Mesh Prism(string name,Vector2[] outline,float height,int[] topTriangles,float uOffset=0){var vertices=new List<Vector3>();var normals=new List<Vector3>();var uv=new List<Vector2>();var sides=new List<int>();var caps=new List<int>();float distance=0;
 for(int i=0;i<outline.Length;i++){var a=outline[i];var b=outline[(i+1)%outline.Length];float length=Vector2.Distance(a,b);var normal=new Vector3(b.y-a.y,0,a.x-b.x).normalized;int index=vertices.Count;vertices.AddRange(new[]{new Vector3(a.x,0,a.y),new Vector3(b.x,0,b.y),new Vector3(b.x,height,b.y),new Vector3(a.x,height,a.y)});normals.AddRange(Enumerable.Repeat(normal,4));float start=(i==0||i==2)?uOffset:distance/2;uv.AddRange(new[]{new Vector2(start,0),new Vector2(start+length/2,0),new Vector2(start+length/2,1),new Vector2(start,1)});sides.AddRange(new[]{index,index+2,index+1,index,index+3,index+2});distance+=length;}
 int top=vertices.Count;foreach(var p in outline){vertices.Add(new Vector3(p.x,height,p.y));normals.Add(Vector3.up);uv.Add(p/2);}for(int i=0;i<topTriangles.Length;i+=3)caps.AddRange(new[]{top+topTriangles[i],top+topTriangles[i+2],top+topTriangles[i+1]});
 int bottom=vertices.Count;foreach(var p in outline){vertices.Add(new Vector3(p.x,0,p.y));normals.Add(Vector3.down);uv.Add(p/2);}for(int i=0;i<topTriangles.Length;i+=3)caps.AddRange(new[]{bottom+topTriangles[i],bottom+topTriangles[i+1],bottom+topTriangles[i+2]});var mesh=new Mesh{name=name};mesh.SetVertices(vertices);mesh.SetNormals(normals);mesh.SetUVs(0,uv);mesh.subMeshCount=2;mesh.SetTriangles(sides,0);mesh.SetTriangles(caps,1);mesh.RecalculateBounds();mesh.RecalculateTangents();return mesh;}
 static Vector2[] Rectangle(float width,float depth)=>new[]{new Vector2(-width/2,-depth/2),new Vector2(width/2,-depth/2),new Vector2(width/2,depth/2),new Vector2(-width/2,depth/2)};
 [MenuItem("Tools/Dungeon Tavern/Build Dungeon Stone Walls")]
 static void Build(){if(AssetDatabase.LoadAssetAtPath<GameObject>(Root+"DungeonWall_2m.prefab"))throw new Exception("Wall kit already exists");Directory.CreateDirectory(Output);var texturePath=Root+"Textures/DungeonStone_Albedo.png";var importer=(TextureImporter)AssetImporter.GetAtPath(texturePath);importer.textureType=TextureImporterType.Default;importer.sRGBTexture=true;importer.npotScale=TextureImporterNPOTScale.None;importer.maxTextureSize=2048;importer.textureCompression=TextureImporterCompression.Uncompressed;importer.mipmapEnabled=false;importer.filterMode=FilterMode.Point;importer.wrapMode=TextureWrapMode.Repeat;importer.SaveAndReimport();var material=new Material(Shader.Find("Universal Render Pipeline/Lit")){name="DungeonStone_Wall"};material.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(texturePath));material.SetColor("_BaseColor",Color.white);material.SetFloat("_Smoothness",.08f);material.SetFloat("_Metallic",0);AssetDatabase.CreateAsset(material,Root+"MAT_DungeonStone_Wall.mat");var cap=new Material(material){name="DungeonStone_Caps"};cap.SetColor("_BaseColor",new Color(.72f,.77f,.8f));AssetDatabase.CreateAsset(cap,Root+"MAT_DungeonStone_Caps.mat");if(!AssetDatabase.IsValidFolder(Root+"Meshes"))AssetDatabase.CreateFolder(Root.TrimEnd('/'),"Meshes");var scene=EditorSceneManager.NewPreviewScene();try{
 void Piece(string name,Vector2[] shape,float height,int[] top,float offset=0,bool concave=false){var mesh=Prism(name,shape,height,top,offset);AssetDatabase.CreateAsset(mesh,Root+"Meshes/"+name+".asset");var go=new GameObject(name);UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(go,scene);go.AddComponent<MeshFilter>().sharedMesh=mesh;go.AddComponent<MeshRenderer>().sharedMaterials=new[]{material,cap};if(concave){go.AddComponent<MeshCollider>().sharedMesh=mesh;}else{var collider=go.AddComponent<BoxCollider>();collider.center=mesh.bounds.center;collider.size=mesh.bounds.size;}PrefabUtility.SaveAsPrefabAsset(go,Root+name+".prefab");UnityEngine.Object.DestroyImmediate(go);}
 var quad=new[]{0,1,2,0,2,3};Piece("DungeonWall_2m",Rectangle(2,.5f),2.875f,quad);Piece("DungeonWall_1m_A",Rectangle(1,.5f),2.875f,quad);Piece("DungeonWall_1m_B",Rectangle(1,.5f),2.875f,quad,.5f);Piece("DungeonWall_Pillar",Rectangle(.7f,.7f),3.025f,quad);Piece("DungeonWall_Corner_L",new[]{new Vector2(-.25f,-.25f),new Vector2(1,-.25f),new Vector2(1,.25f),new Vector2(.25f,.25f),new Vector2(.25f,1),new Vector2(-.25f,1)},2.875f,new[]{0,1,2,0,2,3,0,3,5,3,4,5},0,true);
 var demo=new GameObject("DungeonStoneWalls_Preview");UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(demo,scene);
 void Place(string name,Vector3 pos,float yaw=0){var go=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Root+name+".prefab"),scene);go.transform.SetParent(demo.transform,false);go.transform.localPosition=pos;go.transform.localRotation=Quaternion.Euler(0,yaw,0);}
 Place("DungeonWall_2m",new Vector3(-1,0,1));Place("DungeonWall_2m",new Vector3(1,0,1));Place("DungeonWall_Pillar",new Vector3(2.25f,0,1));Place("DungeonWall_Corner_L",new Vector3(-2.25f,0,1),90);Place("DungeonWall_1m_A",new Vector3(-.5f,0,-1.2f));Place("DungeonWall_1m_B",new Vector3(.5f,0,-1.2f));PrefabUtility.SaveAsPrefabAsset(demo,Root+"DungeonStoneWalls_Preview.prefab");Render(demo);AssetDatabase.SaveAssets();
 }finally{EditorSceneManager.ClosePreviewScene(scene);}File.WriteAllText(Output+"result.txt","Created 5 reusable wall modules and one assembly preview. Wall height 2.875, depth 0.5, main width 2; 1m A/B share complementary UV halves. Pillar 0.7 square, height 3.025. Corner arms extend 1 from pivot. All modules have collision; existing scenes/assets untouched.\n");Selection.activeObject=AssetDatabase.LoadAssetAtPath<GameObject>(Root+"DungeonStoneWalls_Preview.prefab");}
 [MenuItem("Tools/Dungeon Tavern/Check Dungeon Stone Walls")]
 static void Check(){
 var report=new System.Text.StringBuilder();
 foreach(var name in new[]{"DungeonWall_2m","DungeonWall_1m_A","DungeonWall_1m_B","DungeonWall_Pillar","DungeonWall_Corner_L"}){
 var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(Root+name+".prefab");var mesh=prefab.GetComponent<MeshFilter>().sharedMesh;
 if(name=="DungeonWall_1m_A"||name=="DungeonWall_1m_B"){var uv=mesh.uv;float start=name.EndsWith("A")?.5f:0;uv[8].x=uv[11].x=start;uv[9].x=uv[10].x=start+.5f;mesh.uv=uv;mesh.RecalculateTangents();EditorUtility.SetDirty(mesh);}
 if(mesh.subMeshCount!=2||prefab.GetComponent<MeshRenderer>().sharedMaterials.Any(m=>!m)||!prefab.GetComponent<Collider>())throw new Exception(name+" missing mesh/material/collider");
 var v=mesh.vertices;var n=mesh.normals;var triangles=mesh.triangles;for(int i=0;i<triangles.Length;i+=3){int a=triangles[i],b=triangles[i+1],c=triangles[i+2];if(Vector3.Dot(Vector3.Cross(v[b]-v[a],v[c]-v[a]),n[a])<=0)throw new Exception(name+" invalid triangle winding");}
 report.AppendLine(name+": bounds="+mesh.bounds+", materials/collider/winding OK");}
 AssetDatabase.SaveAssets();File.WriteAllText(Output+"check.txt",report.ToString());
 var scene=EditorSceneManager.NewPreviewScene();try{var go=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Root+"DungeonStoneWalls_Preview.prefab"),scene);Render(go);}finally{EditorSceneManager.ClosePreviewScene(scene);}
 AssetDatabase.OpenAsset(AssetDatabase.LoadAssetAtPath<GameObject>(Root+"DungeonStoneWalls_Preview.prefab"));
 }
 static void Render(GameObject root){var scene=root.scene;var go=new GameObject("Preview Camera");UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(go,scene);var camera=go.AddComponent<Camera>();camera.enabled=false;camera.scene=scene;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.11f,.14f,.17f);camera.orthographic=true;camera.orthographicSize=3.7f;camera.nearClipPlane=.01f;camera.farClipPlane=100;var center=new Vector3(0,1.2f,0);camera.transform.position=center+new Vector3(5,4,-7).normalized*12;camera.transform.LookAt(center);go.AddComponent<UniversalAdditionalCameraData>().SetRenderer(1);var lg=new GameObject("Preview Light");UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(lg,scene);var light=lg.AddComponent<Light>();light.type=LightType.Directional;light.intensity=2;lg.transform.rotation=Quaternion.Euler(45,-35,0);var rt=new RenderTexture(1024,768,24);rt.Create();var old=RenderTexture.active;var tex=new Texture2D(1024,768,TextureFormat.RGB24,false);try{RenderPipeline.SubmitRenderRequest(camera,new UniversalRenderPipeline.SingleCameraRequest{destination=rt});RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1024,768),0,0);tex.Apply();File.WriteAllBytes(Output+"KitPreview.png",tex.EncodeToPNG());}finally{RenderTexture.active=old;UnityEngine.Object.DestroyImmediate(tex);rt.Release();UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(go);UnityEngine.Object.DestroyImmediate(lg);}}
}
